openapi: 3.0.3

info: 
  title: Users API
  description: |
    UsersサービスのAPIを提供。
  version: 1.0.0

paths:
  /users:
    get:
      summary: "クエリパラメータでユーザーを検索"
      tags:
        - Users
      parameters:
      - name: query
        in: query
        description: "Number"
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: "ユーザー情報の取得に成功"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    user_id:
                      oneOf:
                        - type: number
                        - type: string
                      description: "ユーザーID"
                    user_name:
                      oneOf:
                        - type: string
                        - type: number
                      description: "ユーザー名。全て数字の場合は数値型もあり得る"
                    friend_ids:
                      type: array
                      items:
                        oneOf:
                          - type: number
                          - type: string
                        nullable: true
                      description: "友達のIDリスト。(文字列と数値の混合配列 or NULL)"
                    birthday:
                      oneOf:
                        - type: string
                          description: "YYYY-MM-DD形式、または、YYY/MM/DD形式"
                        - type: integer
                          description: "Unix timestamp"
                      nullable: true
                      description: "生年月日(文字列 or UnixTimestamp or NULL)"
                    is_active:
                      oneOf:
                        - type: boolean
                        - type: number
                      nullable: true
                      description: "アカウントがアクティブか(boolean or 1 or 0 or NULL)"
        "400":
          description: "クエリパラメータの数値が不正"
          content:
            text/plain:
              schema:
                type: string
                example: "Bad Query String."
        "404":
          description: "検索条件に合うユーザーが一人も見つからなかった"
          content:
            text/plain:
              schema:
                type: string
                example: "User Not Found."
