/* tslint:disable */
/* eslint-disable */
/**
 * Cookie & Session Step1
 * Cookie & Session勉強会 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiStep1ItemsPostRequest
 */
export interface ApiStep1ItemsPostRequest {
    /**
     * 
     * @type {number}
     * @memberof ApiStep1ItemsPostRequest
     */
    item?: number;
}

/**
 * Check if a given object implements the ApiStep1ItemsPostRequest interface.
 */
export function instanceOfApiStep1ItemsPostRequest(value: object): value is ApiStep1ItemsPostRequest {
    return true;
}

export function ApiStep1ItemsPostRequestFromJSON(json: any): ApiStep1ItemsPostRequest {
    return ApiStep1ItemsPostRequestFromJSONTyped(json, false);
}

export function ApiStep1ItemsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiStep1ItemsPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'item': json['item'] == null ? undefined : json['item'],
    };
}

export function ApiStep1ItemsPostRequestToJSON(json: any): ApiStep1ItemsPostRequest {
    return ApiStep1ItemsPostRequestToJSONTyped(json, false);
}

export function ApiStep1ItemsPostRequestToJSONTyped(value?: ApiStep1ItemsPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'item': value['item'],
    };
}

