openapi: 3.0.3

info:
  title: Cookie & Session Step1
  description: |
    Cookie & Session勉強会
  version: 1.0.0

paths:
  /api/step1/items:
    get:
      summary: "カート内の情報を取得"
      tags:
        - Cart
      parameters:
        - in: cookie
          name: cart
          schema:
            type: string
            example: "cart=[{id: 1, quantity: 1}, {id: 2, quantity: 3}]"
      responses:
        "200":
          description: "カート情報の取得に成功"
          content:
            application/json:
              example:
                "cart": [{ "id": 1, "quantity": 1 }, { "id": 2, "quantity": 3 }]
    post:
      summary: "リクエストボディに含まれる商品をCookieに追加"
      tags:
        - Cart
      parameters:
        - in: cookie
          name: cart
          schema:
            type: string
            example: "cart=[{id: 1, quantity: 1}, {id: 2, quantity: 3}]"
      requestBody:
        description: 商品情報
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                item:
                  type: integer
            example:
              "item": 1
      responses:
        "201":
          description: "商品の追加が成功"
          headers:
            Set-Cookie:
              description: カート情報
              schema:
                type: string
                example: "cart=[{id: 1, quantity: 2}, {id: 2, quantity: 3}]; HttpOnly"
          content:
            application/json:
              example:
                "cart": [{ "id": 1, "quantity": 2 }, { "id": 2, "quantity": 3 }]
  /api/step1/items/{itemId}:
    delete:
      summary: "パスに含まれる商品をCookieから削除"
      tags:
        - Cart
      parameters:
        - in: cookie
          name: cart
          schema:
            type: string
            example: "cart=[{id: 1, quantity: 1}, {id: 2, quantity: 3}]"
        - in: path
          required: true
          name: itemId
          schema:
            type: integer
            example: 2
      responses:
        "200":
          description: "商品の削除成功"
          headers:
            Set-Cookie:
              description: カート情報
              schema:
                type: string
                example: "cart=[{id: 1, quantity: 2}]; HttpOnly"
          content:
            application/json:
              example:
                "cart": [{ "id": 1, "quantity": 1 }]
